# Configuration for connection sheets_to_csv
definition_type: connection
resource_name: "sheets_to_csv"
source_configuration_path: sources/sheets/configuration.yaml
destination_configuration_path: destinations/localcsv/configuration.yaml

# EDIT THE CONFIGURATION BELOW!
configuration:
  status: active # REQUIRED | string | Allowed values: active, inactive, deprecated
  skip_reset: false # OPTIONAL | boolean | Flag to check if the connection should be reset after a connection update
  namespace_definition: source # OPTIONAL | string | Allowed values: source, destination, customformat
  namespace_format: "${SOURCE_NAMESPACE}" # OPTIONAL | string | Used when namespaceDefinition is 'customformat'. If blank then behaves like namespaceDefinition = 'destination'. If "${SOURCE_NAMESPACE}" then behaves like namespaceDefinition = 'source'.
  prefix: "" # REQUIRED | Prefix that will be prepended to the name of each stream when it is written to the destination
  resource_requirements: # OPTIONAL | object | Resource requirements to run workers (blank for unbounded allocations)
    cpu_limit: "" # OPTIONAL
    cpu_request: "" # OPTIONAL
    memory_limit: "" # OPTIONAL
    memory_request: "" # OPTIONAL
  schedule_type: basic # OPTIONAL | string | Allowed values: basic, cron, manual
  schedule_data: # OPTIONAL | object
    basic_schedule:
      time_unit: hours # REQUIRED | string | Allowed values: minutes, hours, days, weeks, months
      units: 1 # REQUIRED | integer
    # cron:
    #   cron_time_zone: "UTC" # REQUIRED | string
    #   cron_expression: "* */2 * * * ?" # REQUIRED | string
  sync_catalog: # OPTIONAL | object | 🚨 ONLY edit streams.config, streams.stream should not be edited as schema cannot be changed.
    streams:
      - config:
          alias_name: Sheet1
          cursor_field: []
          destination_sync_mode: append
          primary_key: []
          selected: true
          suggested: true
          sync_mode: full_refresh
        stream:
          default_cursor_field: []
          json_schema:
            $schema: http://json-schema.org/draft-07/schema#
            properties:
              Age:
                $ref: WellKnownTypes.json#/definitions/String
              Gender:
                $ref: WellKnownTypes.json#/definitions/String
              Name:
                $ref: WellKnownTypes.json#/definitions/String
              Profession:
                $ref: WellKnownTypes.json#/definitions/String
              Status:
                $ref: WellKnownTypes.json#/definitions/String
              Student:
                $ref: WellKnownTypes.json#/definitions/String
            type: object
          name: Sheet1
          source_defined_primary_key: []
          supported_sync_modes:
            - full_refresh

